FROM node:18-alpine

WORKDIR /app

COPY ./client-api/package*.json ./

RUN npm install

COPY ./client-api/ ./

COPY ./wait-for.sh /wait-for.sh

RUN npm install --global tsx
RUN npm run prisma-generate

EXPOSE 4000

CMD ["npm", "run", "dev"]
