FROM node:18-alpine

WORKDIR /app

COPY ./client-api/package*.json ./

COPY ./client-api/ ./

COPY ./wait-for.sh /wait-for.sh

RUN npm install

# RUN npm install --global tsx
RUN npm run prisma-generate
RUN npm install @prisma/client

EXPOSE 4000

CMD ["npm", "run", "dev"]
