FROM node:18-alpine

WORKDIR /app

COPY ./import-service/package*.json ./

RUN npm install 

COPY ./import-service/ ./

COPY ./wait-for.sh /wait-for.sh

COPY ./data/poi.json /tmp/poi.json

RUN npm install --global tsx

EXPOSE 4000

CMD ["npm", "run", "dev"]
