FROM node:18-alpine

WORKDIR /app

COPY ./import-service/package*.json ./

COPY ./import-service/ ./

COPY ./wait-for.sh /wait-for.sh

RUN npm install 

# RUN ls 
# ./node_modules
#  | grep mongoose
# RUN npm install reflect-metadata
# RUN npm install mongoose

EXPOSE 4000

CMD ["npm", "run", "dev"]
